### ISSUE TITLE
Breakpoint design tokens are unusable when exported as ready-to-use CSS custom properties

### ISSUE THREAD

**Issue by markus-walther** [axa-ch/design-tokens#4]
https://drafts.csswg.org/css-variables/#defining-variables makes it clear that CSS custom property values cannot be concatenated with fixed strings such as 'px'. The workaround with `calc(...)` is way too cumbersome.

Hence

```css
:root {
    --breakpoints-base-xxl: 1440;
    --breakpoints-base-xl-max: 1439.98;
    --breakpoints-base-xl: 1200;
    --breakpoints-base-lg-max: 1199.98;
    --breakpoints-base-lg: 992;
    --breakpoints-base-md-max: 991.98;
    --breakpoints-base-md: 768;
    --breakpoints-base-sm-max: 767.98;
    --breakpoints-base-sm: 576;
    --breakpoints-base-xs-max: 575.98;
    --breakpoints-base-xs: 0;
}
```

all don't work in real CSS media queries as-is.

Could they instead be exported with 'px' suffixed?
